# syntax=docker/dockerfile:1.3
FROM docker.io/elasticms/base-php:8.1-apache-dev as builder

# include(Args.m4)
# include(Builder.m4)

FROM docker.io/elasticms/base-php:8.1-apache as prd

LABEL be.fgov.elasticms.admin.environment="prd"

# include(Args.m4)
# include(Common.m4)

FROM docker.io/elasticms/base-php:8.1-apache-dev as dev

LABEL be.fgov.elasticms.admin.environment="dev"

# include(Args.m4)
# include(Common.m4)